# Generated by Django 4.0.4 on 2022-12-11 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashish', '0002_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='timestap',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
