# Generated by Django 4.0.4 on 2022-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashish', '0003_expenses_timestap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='timestap',
            field=models.DateField(auto_now_add=True),
        ),
    ]
